### ISSUE TITLE
Bug from AI server: Cannot import name Enum

### ISSUE THREAD

**Issue by ThePlayerZero** [ThePlayerZero/Open-Fantasy#18]
Traceback (most recent call last):
  File "C:\Panda3D-1.11.0-x64\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Panda3D-1.11.0-x64\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Toontown Fantasy\open-fantasy\toontown\ai\AIStart.py", line 43, in <module>
    from otp.ai.AIBaseGlobal import *
  File "E:\Toontown Fantasy\open-fantasy\otp\ai\AIBaseGlobal.py", line 2, in <module>
    __builtins__['simbase'] = AIBase()
  File "E:\Toontown Fantasy\open-fantasy\otp\ai\AIBase.py", line 76, in __init__
    from toontown.pets import PetConstants
  File "E:\Toontown Fantasy\open-fantasy\toontown\pets\PetConstants.py", line 4, in <module>
    from toontown.toonbase import ToontownGlobals
  File "E:\Toontown Fantasy\open-fantasy\toontown\toonbase\ToontownGlobals.py", line 4, in <module>
    from otp.otpbase.PythonUtil import Enum
ImportError: cannot import name 'Enum' from 'otp.otpbase.PythonUtil' (E:\Toontown Fantasy\open-fantasy\otp\otpbase\PythonUtil.py)
Press any key to continue . . .

**Comment by ThePlayerZero** [comment]
Fixed itself...
